In [1]:
import pandas as pd

In [2]:
mcintire_news = pd.read_csv("./data/fake_and_real_news_dataset.csv")

In [3]:
mcintire_news.head()

,idd,title,text,label
0,Fq+C96tcx+,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL
1,bHUqK!pgmv,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL
2,4Y4Ubf%aTi,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL
3,_CoY89SJ@K,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL
4,+rJHoRQVLe,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL

In [4]:
def train_test_split(df):
    
    train_df = df.sample(frac=2/3, random_state=42)
    test_df = df.drop(train_df.index)
    
    return train_df, test_df

In [5]:
mcintire_news_train, mcintire_news_test = train_test_split(mcintire_news)

In [6]:
mcintire_news_train.head()

,idd,title,text,label
3201,mij8ktR1+U,Robert Frank Talks ‘Radical Pragmatism’ and th...,Robert Frank Talks ‘Radical Pragmatism’ and th...,FAKE
2820,$2_rG$!SR!,Latest Pipeline Leak Underscores Dangers Of Da...,"FILE – In this Sept. 15, 2005 file photo, the ...",FAKE
1616,E+&&1TwpM_,Is Hillary Running for Bill’s Third Term?,When Hillary Clinton announces her candidacy o...,REAL
2696,R25v*0goUI,CNN Breaking News: Trump Tells Supporters To V...,\n\nCNN (also known as the Clinton News Networ...,FAKE
3487,_8reyi^4^i,FDNY rope rescue at Manhattan 6th-alarm,Notify me of follow-up comments by email. Noti...,FAKE

In [2]:
3+4

7